run:
  go: '1.23.1'
  concurrency: 4
  issues-exit-code: 1
  tests: true
  modules-download-mode: mod
  allow-parallel-runners: true

linters:
  enable-all: true
  disable:
    - execinquery
    - gomnd
    - exhaustruct
    - nonamedreturns
    - wrapcheck
    - gofumpt
    - gci
    - tagliatelle
    - musttag
    - exportloopref
    - gochecknoglobals
    - mnd

linters-settings:
  gosec:
    excludes:
      - G401
      - G505
      - G306
  misspell:
    ignore-words:
      - sub_payed
  whitespace:
    multi-if: true
    multi-func: false
  lll:
    line-length: 140
  depguard:
    rules:
      main:
        list-mode: lax
        files:
          - $all
        allow:

        deny:
          - pkg: io/ioutil
            desc: "replaced by io and os packages since Go 1.16: https://tip.golang.org/doc/go1.16#ioutil"
  varnamelen:
    ignore-names:
      - ok
      - bs
      - err
      - rv
      - nm
      - tx
      - id
      - wg
      - i
      - db
      - fn
      - tt
  funlen:
    lines: 100
    ignore-comments: true
    statements: 50

issues:
  exclude-rules:
    - linters:
        - lll
      source: ".*// "
